apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask-deployment
  labels:
    app: app-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-flask
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: app-flask
        # image: IMAGE_TAG
        image: asddaniel007/app-flask
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 8080
